#!/usr/bin/bash

hyprctl dispatch exec "kitty --session ~/Documents/Work/Shkolkovo_Boot/scripts_session"
hyprctl dispatch exec "kitty --session ~/Documents/Work/Shkolkovo_Boot/ide_session"
hyprctl dispatch exec "kitty --session ~/Documents/Work/Shkolkovo_Boot/open_session"
hyprctl dispatch exec "thunar ~/Documents/Work/Shkolkovo/"
exit
